name: PHP Linting
on: pull_request
jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@latest
        with:
          preset: laravel
          verboseMode: true
          onlyDirty: true
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
         commit_message: Apply PHP Linting (Pint)
