name: Vercel Deployment

on:
  push:
    branches:
      - placeholder
      - main

env:
  PRODUCTION_BRANCH: placeholder
  PREVIEW_BRANCH: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd frontend && npm install
      - name: vercel-deploy
        run: |
          npx vercel link --yes --project '${{ vars.VERCEL_PROJECT }}' --token '${{ secrets.VERCEL_TOKEN }}'
          if [[ "${{ env.PRODUCTION_BRANCH }}" == "${{ github.ref_name }}" ]]; then
            npx vercel --prod --yes
          else
            npx vercel --yes
          fi
